=begin
#Aspose.Diagram Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end
#rspec spec/api/test_convert_spec.rb

require 'spec_helper'
require 'json'

$fileName="drawingTest.vsdx"

# Unit tests for AsposeDiagramCloud::DiagramApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DrawingApi' do
  before do
    # run before each test
    #@instance = AsposeDiagramCloud::DiagramApi.new($grant_type,$client_id,$client_secret) 
  end

  after do
    # run after each test
  end

  describe 'test an instance of DiagramApi' do
    it 'should create an instance of DiagramApi' do
      expect($diagramApi).to be_instance_of(AsposeDiagramCloud::DiagramApi)
    end
  end

  # unit tests for create_new
  # Create Empty file into the specified format.
  # 
  # @param name The document name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder The document folder.
  # @option opts [BOOLEAN] :is_overwrite If true overwrite the same name file.The default value is false 
  # @return [CreateNewResponse]
  describe 'create_new test' do
    it "should work" do
      name = $fileName
      folder = $storageTestFOLDER
      is_overwrite=true
      result=$diagramApi.create_new(name,  {:name=>name, :is_overwrite=>is_overwrite, :folder=>folder})
      #print(result)
      expect(result.created).not_to be_empty
      #assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'put_draw_line test' do
    it "should work" do
      folder = $storageTestFOLDER
      draw_data=AsposeDiagramCloud::LineData.new
      draw_data.pin_x = 1
      draw_data.pin_y = 2
      draw_data.width = 1
      draw_data.height = 1
      draw_data.points =[AsposeDiagramCloud::PointF.new({"X"=>1,"Y"=>0}),AsposeDiagramCloud::PointF.new({"X"=>1,"Y"=>1})]
      draw_data.text = "test draw line"
      shapeStyleData = AsposeDiagramCloud::ShapeStyleData.new
      shapeStyleData.back_ground_color = "#FF0000"
      textStyleData = AsposeDiagramCloud::TextStyleData.new
      textStyleData.font_size = 0.2
      textStyleData.font_name = "Times New Roman"
      draw_data.shape_style_data = shapeStyleData
      draw_data.text_style_data = textStyleData
      result=$diagramApi.put_draw_line($fileName,"Page-0", draw_data,{:folder=>folder})
      #print(result)
      expect(result.is_success).to be_truthy 
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'put_draw_ellipse test' do
    it "should work" do
      folder = $storageTestFOLDER
      draw_data=AsposeDiagramCloud::EllipseData.new
      draw_data.pin_x = 5
      draw_data.pin_y = 5
      draw_data.width = 1
      draw_data.height = 1
      draw_data.text = "test draw ellipse"
      shapeStyleData = AsposeDiagramCloud::ShapeStyleData.new
      shapeStyleData.back_ground_color = "#FF0000"
      textStyleData = AsposeDiagramCloud::TextStyleData.new
      textStyleData.font_size = 0.2
      textStyleData.font_name = "Times New Roman"
      draw_data.shape_style_data = shapeStyleData
      draw_data.text_style_data = textStyleData
      result=$diagramApi.put_draw_ellipse($fileName,"Page-0", draw_data,{:folder=>folder})
      #print(result)
      expect(result.is_success).to be_truthy 
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'put_draw_polyline test' do
    it "should work" do
      folder = $storageTestFOLDER
      draw_data=AsposeDiagramCloud::PolylineData.new
      draw_data.pin_x = 3
      draw_data.pin_y = 3
      draw_data.width = 1
      draw_data.height = 1
      draw_data.points =[AsposeDiagramCloud::PointF.new({"X"=>0,"Y"=>0}),
        AsposeDiagramCloud::PointF.new({"X"=>0,"Y"=>1}),
        AsposeDiagramCloud::PointF.new({"X"=>1,"Y"=>1}),
        AsposeDiagramCloud::PointF.new({"X"=>1,"Y"=>0})
      ]
      draw_data.text = "test draw polyline"
      shapeStyleData = AsposeDiagramCloud::ShapeStyleData.new
      shapeStyleData.back_ground_color = "#FF0000"
      textStyleData = AsposeDiagramCloud::TextStyleData.new
      textStyleData.font_size = 0.2
      textStyleData.font_name = "Times New Roman"
      draw_data.shape_style_data = shapeStyleData
      draw_data.text_style_data = textStyleData
      result=$diagramApi.put_draw_polyline($fileName,"Page-0", draw_data,{:folder=>folder})
      #print(result)
      expect(result.is_success).to be_truthy 
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

 


end
