=begin
#Aspose.Diagram Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

# Common files
require 'AsposeDiagramCloud/api_client'
require 'AsposeDiagramCloud/api_error'
require 'AsposeDiagramCloud/version'
require 'AsposeDiagramCloud/configuration'

# Models
require 'AsposeDiagramCloud/models/access_token_response'
require 'AsposeDiagramCloud/models/disc_usage'
require 'AsposeDiagramCloud/models/error'
require 'AsposeDiagramCloud/models/error_details'
require 'AsposeDiagramCloud/models/file_versions'
require 'AsposeDiagramCloud/models/files_list'
require 'AsposeDiagramCloud/models/files_upload_result'
require 'AsposeDiagramCloud/models/object_exist'
require 'AsposeDiagramCloud/models/page_size'
require 'AsposeDiagramCloud/models/pdf_digital_signature_details'
require 'AsposeDiagramCloud/models/pdf_encryption_details'
require 'AsposeDiagramCloud/models/point_f'
require 'AsposeDiagramCloud/models/rectangle_f'
require 'AsposeDiagramCloud/models/saa_spose_response'
require 'AsposeDiagramCloud/models/save_options_model'
require 'AsposeDiagramCloud/models/save_options_request'
require 'AsposeDiagramCloud/models/storage_exist'
require 'AsposeDiagramCloud/models/storage_file'
require 'AsposeDiagramCloud/models/create_new_response'
require 'AsposeDiagramCloud/models/diagram_save_options'
require 'AsposeDiagramCloud/models/file_version'
require 'AsposeDiagramCloud/models/modify_response'
require 'AsposeDiagramCloud/models/rendering_save_options'
require 'AsposeDiagramCloud/models/swf_save_options'
require 'AsposeDiagramCloud/models/save_as_response'
require 'AsposeDiagramCloud/models/upload_response'
require 'AsposeDiagramCloud/models/xaml_save_options'
require 'AsposeDiagramCloud/models/xps_save_options'
require 'AsposeDiagramCloud/models/html_save_options'
require 'AsposeDiagramCloud/models/image_save_options'
require 'AsposeDiagramCloud/models/pdf_save_options'
require 'AsposeDiagramCloud/models/svg_save_options'

# APIs
require 'AsposeDiagramCloud/api/diagram_api'
require 'AsposeDiagramCloud/api/o_auth_api'
require 'AsposeDiagramCloud/api/storage_api'

module AsposeDiagramCloud
  class << self
    # Customize default settings for the SDK using block.
    #   AsposeDiagramCloud.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
