=begin
#Web API Swagger specification

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

# Common files
require 'aspose_diagram_cloud/api_client'
require 'aspose_diagram_cloud/api_error'
require 'aspose_diagram_cloud/version'
require 'aspose_diagram_cloud/configuration'

# Models
require 'aspose_diagram_cloud/models/access_token_response'
require 'aspose_diagram_cloud/models/diagram_model'
require 'aspose_diagram_cloud/models/file_format_request'
require 'aspose_diagram_cloud/models/link'
require 'aspose_diagram_cloud/models/page_model'
require 'aspose_diagram_cloud/models/saa_spose_response'
require 'aspose_diagram_cloud/models/save_result'
require 'aspose_diagram_cloud/models/sharp_model'
require 'aspose_diagram_cloud/models/diagram_response'
require 'aspose_diagram_cloud/models/save_response'

# APIs
require 'aspose_diagram_cloud/api/diagram_file_api'
require 'aspose_diagram_cloud/api/o_auth_api'

module AsposeDiagramCloud
  class << self
    # Customize default settings for the SDK using block.
    #   AsposeDiagramCloud.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
